---
title: "Descriptives - Fathers' analysis"
format: docx
editor: visual
execute:
  echo: false
  message: false
  warning: false
---

```{r setup}

# packages ----------------------------------------------------------------
packages <- c("tidyverse", "here", "gtsummary", "labelled")
groundhog_day <- "2024-01-11"

# (install and) load package versions available on the specified day to try
# to ensure reproducibility

library(groundhog)

groundhog::meta.groundhog(groundhog_day)

groundhog::groundhog.library(pkg = packages, date = groundhog_day)

# to make the tables more APA friendly. comment out this code if not desired

groundhog::groundhog.library(pkg = "github::benediktclaus/benelib", date = groundhog_day) # from devtools::install_github("benediktclaus/benelib")
benelib::theme_gtsummary_apa(set_theme = TRUE)

dat <- readRDS(file = here::here("01_data-processing", "data_private", "data_final.RDS")) |> 
  select(
    starts_with("f_"),
    ends_with("prop"),
    -contains("sample")
  ) |> 
  dplyr::mutate(
    ipv_binary = ifelse(ipv_prop > 0, 1, 0)
  )

dat_imputed <- readRDS(file = here::here("01_data-processing", "data_private", "data_final_imputed_cases.RDS")) |> 
  select(
    starts_with("f_"),
    ends_with("prop"),
    -contains("sample")
  )|> 
  dplyr::mutate(
    ipv_binary = ifelse(ipv_prop > 0, 1, 0)
  )

```

# Descriptives before data imputation

```{r}
dat |> 
  labelled::remove_var_label() |> 
  gtsummary::tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd}), {min} - {max}"),
    digits = list(all_continuous() ~ 2, all_categorical() ~ 2),
    type = list(c("ipv_physical_prop", "ipv_controlling_prop", "ipv_emotional_prop") ~ "continuous"), missing = "ifany" 
  ) 
```

# Descriptives after data imputation

```{r}
dat_imputed |> 
  labelled::remove_var_label() |> 
  gtsummary::tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd}), {min} - {max}"),
    digits = list(all_continuous() ~ 2, all_categorical() ~ 2),
    type = list(c("ipv_physical_prop", "ipv_controlling_prop", "ipv_emotional_prop") ~ "continuous") 
  )
```
